### ISSUE TITLE
Missing bulma reference in packages.json

### ISSUE THREAD

**Issue by pdifeo** [fl2top/laravel-file-hosting#1]
Missing bulma reference in packages.json

ERROR in ./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/lib??postcss!./node_modules/sass-loader/lib/loader.js??ref--8-4!./resources/assets/sass/app.scss
Module build failed:
@import "~bulma/bulma.sass";

**Comment by fl2top** [comment]
@pdifeo yeah, it is a problem. Thank you, I'll fix it as soon as possible.

**Comment by mitrallex** [comment]
@pdifeo yeah, it is a problem. Thank you, I'll fix it as soon as possible.
